version: '3.8'
services:
  oracle-db:
    image:  container-registry.oracle.com/database/free:23.26.0.0-lite
    container_name: oracle-demo
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: "YourPassword123"
    volumes:
      - oracle-data:/opt/oracle/oradata # Path for persistent data

  redis:
    image: redis:8.4.0
    container_name: redis-demo
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
      
volumes:
  oracle-data:
  redis-data: